version = 0.1

[default.deploy.parameters]
stack_name = "hr-vacancy-bot"
resolve_s3 = true
s3_prefix = "hr-vacancy-bot"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = []
image_repositories = []

[default.global.parameters]
region = "eu-central-1"
